server:
  port: 8081

spring:
  application:
    name: deal
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:postgresql://localhost:5432/creditbank_db
    password: password
    username: creditbank_user
