server:
  port: 8082

spring:
  application:
    name: statement

statement:
  deal-statement-url: http://localhost:8080/deal/statement
  deal-offer-select-url: http://localhost:8080/deal/offer/select