server:
  port: 8083

spring:
  application:
    name: dossier

  kafka:
    bootstrap-servers: localhost:9092

  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    username: ${YANDEX_SMTP_USERNAME}
    password: ${YANDEX_SMTP_PASSWORD}

dossier:
  topics:
    FINISH_REGISTRATION: ${FINISH_REGISTRATION_TOPIC}
    CREATE_DOCUMENTS: ${CREATE_DOCUMENTS_TOPIC}
    SEND_DOCUMENTS: ${SEND_DOCUMENTS_TOPIC}
    SEND_SES: ${SEND_SES_TOPIC}
    CREDIT_ISSUED: ${CREDIT_ISSUED_TOPIC}
    STATEMENT_DENIED: ${STATEMENT_DENIED_TOPIC}